In [1]:
import torch



### Exercise 1: Basic Replacement (1D)

Replace all negative values in the tensor `x` with values from `src`.

In [3]:
x = torch.tensor([3, -1, 4, -5, 2])
src = torch.tensor([10, 20])

# TODO: Replace negative elements in x using masked_scatter

mask = x < 0
result = torch.masked_scatter(x, mask, src)
result

tensor([ 3, 10,  4, 20,  2])

### Exercise 2: Matrix Masking (2D)

Replace all values in `x` greater than 5 with values from `src`.

In [5]:
x = torch.tensor([
    [1, 6],
    [7, 3]
])
src = torch.tensor([100, 200])

# TODO: Replace elements > 5
mask = x > 5

result = torch.masked_scatter(x, mask, src) # Because x and src are broadcasted
result

tensor([[  1, 100],
        [200,   3]])

### Exercise 3: In-Place Masked Scatter

Do an in-place masked scatter on a tensor `x` where values divisible by 3 should be replaced with values from `src`.

In [8]:
x = torch.tensor([3, 5, 6, 7, 9])
src = torch.tensor([111, 222, 333])

# TODO: Replace divisible-by-3 elements using in-place op
mask = (x % 3 == 0)
result = torch.masked_scatter(x, mask, src)
result

tensor([111,   5, 222,   7, 333])